### ISSUE TITLE
Feature request: ability to disable `--bail` in CI

### ISSUE THREAD

**Issue by dreamorosi** [webdeveric/validate-package-exports#6]
Currently the `--bail` flag is enabled by default when running in CI environments. 

If possible, it'd be great if users could override this behavior and disable the bail mechanism even when running CI.

From what I can tell it should be possible by allowing the `--bail` flag to take a boolean argument, this way users could do `--bail=false` to explicitly disable bailing.

**Comment by webdeveric** [comment]
@dreamorosi I've added `--no-bail` that lets you force `bail` to be `false`.

A new version has been published.
